In [12]:
import numpy as np
import pandas as pd

In [13]:
df=pd.read_csv('/content/Coffe_sales - Coffe_sales.csv')
df.head(5)

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:51
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:23
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:15

In [14]:
df.isnull().sum()

hour_of_day    0
cash_type      0
money          0
coffee_name    0
Time_of_Day    0
Weekday        0
Month_name     0
Weekdaysort    0
Monthsort      0
Date           0
Time           0
dtype: int64

In [15]:
x=df.drop(columns=['money'])
y=df['money']

In [16]:
x.head(5)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:51
1,12,card,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:23
2,12,card,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18
3,13,card,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33
4,13,card,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:15

In [19]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

x['Time_of_Day']=lb.fit_transform(x['Time_of_Day'])
x['Month_name']=lb.fit_transform(x['Month_name'])
x['Weekday']=lb.fit_transform(x['Weekday'])
x['cash_type']=lb.fit_transform(x['cash_type'])
x['coffee_name']=lb.fit_transform(x['coffee_name'])
x['Time_of_Day']=lb.fit_transform(x['Time_of_Day'])
x.head(5)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,0,7,1,0,7,5,3,2024-03-01,10:15:51
1,12,0,6,0,0,7,5,3,2024-03-01,12:19:23
2,12,0,6,0,0,7,5,3,2024-03-01,12:20:18
3,13,0,0,0,0,7,5,3,2024-03-01,13:46:33
4,13,0,7,0,0,7,5,3,2024-03-01,13:48:15

In [20]:
x=x.drop(columns=['Date','Time'])
x.head(5)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,10,0,7,1,0,7,5,3
1,12,0,6,0,0,7,5,3
2,12,0,6,0,0,7,5,3
3,13,0,0,0,0,7,5,3
4,13,0,7,0,0,7,5,3

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)

In [23]:
x_train_sc_df=pd.DataFrame(x_train_sc,columns=x_train.columns)
x_train_sc_df.head(5)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,-1.232143,0.0,-0.843880,0.018905,-1.469657,1.186363,0.588278,1.017897
1,-0.288155,0.0,-0.843880,-1.200058,-0.980691,-0.874697,-1.442686,-1.263350
2,-0.760149,0.0,-1.227856,0.018905,1.464142,-0.874697,-0.427204,-1.263350
3,0.891832,0.0,-1.227856,1.237868,-0.002758,-1.463572,1.603760,0.447585
4,1.363826,0.0,1.459974,1.237868,0.975175,-1.463572,-0.934945,0.447585

In [24]:
np.round(x_train_sc_df.describe(),2)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
count,2837.00,2837.0,2837.00,2837.00,2837.00,2837.00,2837.00,2837.00
mean,-0.00,0.0,0.00,-0.00,0.00,0.00,-0.00,0.00
std,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.94,0.0,-1.23,-1.20,-1.47,-1.76,-1.44,-1.55
25%,-1.00,0.0,-0.84,-1.20,-0.98,-0.87,-0.93,-0.98
50%,-0.05,0.0,-0.46,0.02,-0.00,0.01,0.08,0.16
75%,0.89,0.0,1.08,1.24,0.98,0.89,0.59,1.02
max,1.84,0.0,1.46,1.24,1.46,1.48,1.60,1.59

In [ ]:
-- -----------------------------------------------------

In [41]:
df=pd.read_csv('/content/Coffe_sales - Coffe_sales.csv')
df.head(5)

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:51
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:23
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:15

In [42]:
df=df.drop(columns=['Date','Time'])
df.head(5)

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3

In [43]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
df['Time_of_Day']=oe.fit_transform(df[['Time_of_Day']])
df['Month_name']=oe.fit_transform(df[['Month_name']])
df['Weekday']=oe.fit_transform(df[['Weekday']])
df['cash_type']=oe.fit_transform(df[['cash_type']])
df['coffee_name']=oe.fit_transform(df[['coffee_name']])
df.head(5)

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,10,0.0,38.7,7.0,1.0,0.0,7.0,5,3
1,12,0.0,38.7,6.0,0.0,0.0,7.0,5,3
2,12,0.0,38.7,6.0,0.0,0.0,7.0,5,3
3,13,0.0,28.9,0.0,0.0,0.0,7.0,5,3
4,13,0.0,38.7,7.0,0.0,0.0,7.0,5,3

In [44]:
x=df.drop(columns=['money'])
y=df['money']

In [45]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [46]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
x_train_ms=ms.fit_transform(x_train)

In [47]:
x_train_ms_df=pd.DataFrame(x_train_ms,columns=x_train.columns)
x_train_ms_df.head(5)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,0.7500,0.0,1.000000,1.0,0.166667,1.000000,0.000000,0.727273
1,0.2500,0.0,0.571429,0.5,1.000000,0.090909,0.333333,0.636364
2,0.6875,0.0,0.142857,1.0,0.833333,0.272727,0.166667,0.090909
3,0.6875,0.0,0.571429,1.0,0.333333,0.363636,0.833333,0.000000
4,0.4375,0.0,0.000000,0.0,0.500000,0.818182,1.000000,0.909091

In [48]:
np.round(x_train_ms_df.describe(),2)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
count,2837.00,2837.0,2837.00,2837.00,2837.00,2837.00,2837.00,2837.00
mean,0.51,0.0,0.45,0.49,0.50,0.54,0.47,0.50
std,0.26,0.0,0.37,0.41,0.34,0.31,0.33,0.32
min,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.25,0.0,0.14,0.00,0.17,0.27,0.17,0.18
50%,0.50,0.0,0.29,0.50,0.50,0.55,0.50,0.55
75%,0.75,0.0,0.86,1.00,0.83,0.82,0.83,0.82
max,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00

In [52]:
x_train_ms_df.iloc[30:40,:3]

    hour_of_day  cash_type  coffee_name
30       0.3125        0.0     1.000000
31       0.1875        0.0     0.285714
32       0.8125        0.0     1.000000
33       0.8125        0.0     1.000000
34       0.9375        0.0     0.857143
35       0.1875        0.0     1.000000
36       0.3750        0.0     0.142857
37       0.1250        0.0     0.000000
38       0.9375        0.0     0.142857
39       0.3125        0.0     1.000000

In [53]:
x_train_ms_df.rename(columns={'Time_of_Day':'Time_day'},inplace=True)

In [54]:
x_train_ms_df.head(5)

,hour_of_day,cash_type,coffee_name,Time_day,Weekday,Month_name,Weekdaysort,Monthsort
0,0.7500,0.0,1.000000,1.0,0.166667,1.000000,0.000000,0.727273
1,0.2500,0.0,0.571429,0.5,1.000000,0.090909,0.333333,0.636364
2,0.6875,0.0,0.142857,1.0,0.833333,0.272727,0.166667,0.090909
3,0.6875,0.0,0.571429,1.0,0.333333,0.363636,0.833333,0.000000
4,0.4375,0.0,0.000000,0.0,0.500000,0.818182,1.000000,0.909091