In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/placement - placement.csv")
df.sample(10)

    cgpa  resume_score  placed
3   6.88          7.27       1
50  8.22          6.74       1
48  5.54          6.57       0
5   8.77          6.19       1
45  8.10          5.44       1
55  6.94          6.87       1
4   7.52          7.30       1
96  8.23          7.76       1
69  8.06          9.06       1
83  7.60          8.08       1

In [ ]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [ ]:
df.shape

(100, 3)

In [ ]:
x=df.drop(columns=["placed"])
y=df["placed"]

In [ ]:
x

    cgpa  resume_score
0   8.14          6.52
1   6.17          5.17
2   8.27          8.86
3   6.88          7.27
4   7.52          7.30
..   ...           ...
95  6.33          6.38
96  8.23          7.76
97  6.65          7.78
98  8.14          5.63
99  6.09          6.61

[100 rows x 2 columns]

In [ ]:
y

0     1
1     0
2     1
3     1
4     1
     ..
95    0
96    1
97    0
98    1
99    0
Name: placed, Length: 100, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
print("Total data shsap:",df.shape)
print("--------------------------------")
print("input data shap:",x.shape)
print("x_train shape:",x_train.shape)
print("x_test shape:",x_test.shape)
print("------------------------------")
print("targe data shap:",y.shape)
print("y_train shape:",y_train.shape)
print("y_test shape:",y_test.shape)

Total data shsap: (100, 3)
--------------------------------
input data shap: (100, 2)
x_train shape: (80, 2)
x_test shape: (20, 2)
------------------------------
targe data shap: (100,)
y_train shape: (80,)
y_test shape: (20,)

02/04/2026

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/insurance - insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [ ]:
df=df.drop(columns=['region','smoker'])

In [ ]:
df.head(2)

   age     sex    bmi  children     charges
0   19  female  27.90         0  16884.9240
1   18    male  33.77         1   1725.5523

In [ ]:
df['sex']=df['sex'].map({'female':0,'male':1})

In [ ]:
df.head(2)

   age  sex    bmi  children     charges
0   19    0  27.90         0  16884.9240
1   18    1  33.77         1   1725.5523

In [ ]:
x=df.drop(columns=['charges'])  #input
y=df['charges']# target

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
np.round(x_train.head(2),2)

     age  sex   bmi  children
708   31    0  30.5         3
45    55    1  37.3         0

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)

In [ ]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

           age      sex      bmi  children
count  1070.00  1070.00  1070.00   1070.00
mean      0.00    -0.00     0.00     -0.00
std       1.00     1.00     1.00      1.00
min      -1.54    -1.01    -2.38     -0.90
25%      -0.89    -1.01    -0.72     -0.90
50%       0.03     0.99    -0.05     -0.08
75%       0.89     0.99     0.63      0.73
max       1.74     0.99     3.60      3.18

In [ ]:
df=pd.read_csv("/content/tips.csv")
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
df['sex']=df['sex'].map({'Female':0,'Male':1})
df['smoker']=df['smoker'].map({'No':0,'Yes':1})
df['day']=df['day'].map({'Thur':0,'Fri':1,'Sat':2,'Sun':3})

In [ ]:
df.head(2)

   total_bill   tip  sex  smoker  day    time  size
0       16.99  1.01    0       0    3  Dinner     2
1       10.34  1.66    1       0    3  Dinner     3

In [ ]:
df=df.drop(columns=['time'])

In [ ]:
df.head(2)

   total_bill   tip  sex  smoker  day  size
0       16.99  1.01    0       0    3     2
1       10.34  1.66    1       0    3     3

In [ ]:
x=df.drop(columns=['total_bill'])
y=df['total_bill']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=21)

In [ ]:
np.round(x_train.describe(),2)

          tip     sex  smoker     day    size
count  195.00  195.00  195.00  195.00  195.00
mean     3.03    0.65    0.37    1.72    2.58
std      1.44    0.48    0.49    1.17    0.97
min      1.00    0.00    0.00    0.00    1.00
25%      2.00    0.00    0.00    0.00    2.00
50%      2.92    1.00    0.00    2.00    2.00
75%      3.60    1.00    1.00    3.00    3.00
max     10.00    1.00    1.00    3.00    6.00

In [ ]:
sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)

In [ ]:
x_train_new1=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [ ]:
np.round(x_train_new1.describe(),2)

          tip     sex  smoker     day    size
count  195.00  195.00  195.00  195.00  195.00
mean    -0.00   -0.00   -0.00    0.00   -0.00
std      1.00    1.00    1.00    1.00    1.00
min     -1.41   -1.37   -0.77   -1.48   -1.64
25%     -0.72   -1.37   -0.77   -1.48   -0.61
50%     -0.08    0.73   -0.77    0.24   -0.61
75%      0.40    0.73    1.29    1.10    0.43
max      4.84    0.73    1.29    1.10    3.54

----------07/04/2026----

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/placement - placement.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/placement - placement.csv'

In [ ]:
x=df.drop(columns=['placed'])
y=df['placed']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
np.round(x_test.describe(),2)

        cgpa  resume_score
count  20.00         20.00
mean    7.03          7.09
std     0.97          1.00
min     5.62          4.95
25%     6.14          6.72
50%     6.92          7.20
75%     7.82          7.77
max     9.05          8.71

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn=MinMaxScaler()
x_train_mn=mn.fit_transform(x_train)

In [ ]:
x_train_new2=pd.DataFrame(x_train_mn,columns=x_train.columns)

In [ ]:
np.round(x_train_new2.describe(),2)

        cgpa  resume_score
count  80.00         80.00
mean    0.40          0.45
std     0.28          0.25
min     0.00          0.00
25%     0.16          0.28
50%     0.31          0.48
75%     0.68          0.63
max     1.00          1.00

-- 08/04/2026----

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/tips.csv')
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.dropna()

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb=LabelEncoder()

In [ ]:
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['day']=lb.fit_transform(df['day'])
df['time']=lb.fit_transform(df['time'])

In [ ]:
df.head(2)

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3

In [ ]:
x=df.drop(columns=['total_bill'])
y=df['total_bill']

In [ ]:
import sklearn.model_selection as train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

TypeError: 'module' object is not callable

In [ ]:
df=pd.read_csv('/content/insurance - insurance.csv')
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [ ]:
df.dropna()
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['region']=lb.fit_transform(df['region'])

In [ ]:
df.head(5)

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [ ]:
x=df.drop(columns=['charges'])
y=df['charges']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
np.round(x_train.describe(),2)

           age     sex      bmi  children   smoker  region
count  1070.00  1070.0  1070.00   1070.00  1070.00  1070.0
mean     39.56     0.5    30.77      1.10     0.21     1.5
std      14.05     0.5     6.22      1.23     0.41     1.1
min      18.00     0.0    15.96      0.00     0.00     0.0
25%      27.00     0.0    26.30      0.00     0.00     1.0
50%      40.00     1.0    30.50      1.00     0.00     2.0
75%      52.00     1.0    34.69      2.00     0.00     2.0
max      64.00     1.0    53.13      5.00     1.00     3.0

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ss=StandardScaler()
x_train_ss=ss.fit_transform(x_train)

In [ ]:
x_train_new3=pd.DataFrame(x_train_ss,columns=x_train.columns)

In [ ]:
np.round(x_train_new3.describe(),2)

           age      sex      bmi  children   smoker   region
count  1070.00  1070.00  1070.00   1070.00  1070.00  1070.00
mean      0.00    -0.00     0.00     -0.00    -0.00    -0.00
std       1.00     1.00     1.00      1.00     1.00     1.00
min      -1.54    -1.01    -2.38     -0.90    -0.51    -1.37
25%      -0.89    -1.01    -0.72     -0.90    -0.51    -0.46
50%       0.03     0.99    -0.05     -0.08    -0.51     0.45
75%       0.89     0.99     0.63      0.73    -0.51     0.45
max       1.74     0.99     3.60      3.18     1.96     1.36

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mm=MinMaxScaler()
x_train_mm=mm.fit_transform(x_train)

In [ ]:
x_train_new4=pd.DataFrame(x_train_mm,columns=x_train.columns)

In [ ]:
np.round(x_train_new4.describe(),2)

           age     sex      bmi  children   smoker   region
count  1070.00  1070.0  1070.00   1070.00  1070.00  1070.00
mean      0.47     0.5     0.40      0.22     0.21     0.50
std       0.31     0.5     0.17      0.25     0.41     0.37
min       0.00     0.0     0.00      0.00     0.00     0.00
25%       0.20     0.0     0.28      0.00     0.00     0.33
50%       0.48     1.0     0.39      0.20     0.00     0.67
75%       0.74     1.0     0.50      0.40     0.00     0.67
max       1.00     1.0     1.00      1.00     1.00     1.00

---- 10/04/2026-------

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/tips.csv')
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
df=df.dropna()

In [ ]:
a=pd.get_dummies(df,columns=['sex','smoker','day','time'])
a.head(2)

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,16.99,1.01,2,True,False,True,False,False,False,True,False,True,False
1,10.34,1.66,3,False,True,True,False,False,False,True,False,True,False

In [ ]:
a=a.astype(int)

In [ ]:
b=pd.get_dummies(df,columns=['sex','smoker','day','time'],drop_first=True)
b.head(2)

,total_bill,tip,size,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch
0,16.99,1.01,2,False,False,False,True,False,False
1,10.34,1.66,3,True,False,False,True,False,False

In [ ]:
b=b.astype(int)
b.head(5)

,total_bill,tip,size,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch
0,16,1,2,0,0,0,1,0,0
1,10,1,3,1,0,0,1,0,0
2,21,3,3,1,0,0,1,0,0
3,23,3,2,1,0,0,1,0,0
4,24,3,4,0,0,0,1,0,0

In [2]:
import numpy as np
import pandas as pd

- sunday parcties

In [25]:
df=pd.read_csv('/content/cars - cars.csv')
df.head(10)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC BSII,1992,50000,100000,Petrol,Individual,Manual,Fourth & Above Owner
1,Maruti Gypsy E MG410W ST,1995,95000,100000,Petrol,Individual,Manual,Second Owner
2,Mahindra Jeep CL 500 MDI,1996,250000,35000,Diesel,Individual,Manual,Second Owner
3,Mahindra Jeep MM 540,1996,200000,60000,Diesel,Individual,Manual,First Owner
4,Mahindra Jeep CL 500 MDI,1997,150000,120000,Diesel,Individual,Manual,Third Owner
5,Maruti Esteem AX,1997,79000,70000,Petrol,Individual,Automatic,First Owner
6,Maruti 800 Std,1997,50000,80000,Petrol,Individual,Manual,Second Owner
7,Maruti 800 Std,1998,40000,40000,Petrol,Individual,Manual,Fourth & Above Owner
8,Maruti Omni 5 Str STD LPG,1998,50000,35000,LPG,Individual,Manual,Second Owner
9,Maruti Zen LXI,1998,69000,70000,Petrol,Individual,Manual,Second Owner

In [4]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [7]:
df['seller_type'].value_counts()

seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64

In [8]:
df['transmission'].value_counts()

transmission
Manual       3892
Automatic     448
Name: count, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [13]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='object')

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
LE=LabelEncoder()

In [28]:
df['seller_type']=LE.fit_transform(df['seller_type'])
df['transmission']=LE.fit_transform(df['transmission'])
df['owner']=LE.fit_transform(df['owner'])
df['fuel']=LE.fit_transform(df['fuel'])

In [29]:
df.head(5)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC BSII,1992,50000,100000,4,1,1,1
1,Maruti Gypsy E MG410W ST,1995,95000,100000,4,1,1,2
2,Mahindra Jeep CL 500 MDI,1996,250000,35000,1,1,1,2
3,Mahindra Jeep MM 540,1996,200000,60000,1,1,1,0
4,Mahindra Jeep CL 500 MDI,1997,150000,120000,1,1,1,4

In [19]:
df['name'].value_counts()

name
Maruti Swift Dzire VDI                   69
Maruti Alto 800 LXI                      59
Maruti Alto LXi                          47
Hyundai EON Era Plus                     35
Maruti Alto LX                           35
                                         ..
Hyundai Elite i20 Magna Plus BSIV         1
Maruti Alto K10 LX                        1
Hyundai Grand i10 Nios AMT Magna          1
Hyundai Grand i10 Nios Sportz             1
Volkswagen Polo 1.0 TSI Highline Plus     1
Name: count, Length: 1491, dtype: int64

In [32]:
df['brand']=df['name'].str.split().str.get(0)

In [33]:
df['brand'].value_counts()

brand
Maruti           1280
Hyundai           821
Mahindra          365
Tata              361
Honda             252
Ford              238
Toyota            206
Chevrolet         188
Renault           146
Volkswagen        107
Skoda              68
Nissan             64
Audi               60
BMW                39
Fiat               37
Datsun             37
Mercedes-Benz      35
Jaguar              6
Mitsubishi          6
Land                5
Ambassador          4
Volvo               4
Jeep                3
MG                  2
OpelCorsa           2
Daewoo              1
Force               1
Isuzu               1
Kia                 1
Name: count, dtype: int64

In [34]:
df['brand']=LE.fit_transform(df['brand'])

- -----------------------------------------------------------

In [57]:
df=pd.read_csv('/content/click - click.csv')
df.head(2)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Gender,Country,Timestamp,Clicked on Ad
0,62.26,32,69481.85,172.83,Decentralized real-time circuit,Lisafort,Male,Svalbard & Jan Mayen Islands,2016-06-09 21:43:05,0
1,41.73,31,61840.26,207.17,Optional full-range projection,West Angelabury,Male,Singapore,2016-01-16 17:56:05,0

In [58]:
df.drop(columns=['City','Country','Timestamp'],inplace=True)

In [59]:
df.drop(columns=['Ad Topic Line'],inplace=True)

In [60]:
df.head(2)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Gender,Clicked on Ad
0,62.26,32,69481.85,172.83,Male,0
1,41.73,31,61840.26,207.17,Male,0

In [61]:
from sklearn.preprocessing import LabelEncoder

In [62]:
lb=LabelEncoder()

In [63]:
df['Gender']=lb.fit_transform(df['Gender'])

In [64]:
df.head(5)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Gender,Clicked on Ad
0,62.26,32,69481.85,172.83,1,0
1,41.73,31,61840.26,207.17,1,0
2,44.40,30,57877.15,172.83,0,0
3,59.88,28,56180.93,207.17,0,0
4,49.21,30,54324.73,201.58,0,1

In [65]:
x=df.drop(columns=['Clicked on Ad'])
y=df['Clicked on Ad']

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [68]:
from sklearn.preprocessing import StandardScaler

In [69]:
sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)

In [70]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [71]:
np.round(x_train_new.describe(),2)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Gender
count,8000.00,8000.00,8000.00,8000.00,8000.00
mean,-0.00,0.00,-0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00
min,-1.84,-1.98,-2.99,-1.77,-0.93
25%,-0.88,-0.81,-0.74,-0.91,-0.93
50%,-0.12,-0.11,0.17,0.04,-0.93
75%,0.95,0.71,0.61,0.86,1.07
max,1.87,2.81,1.92,2.27,1.07