In [18]:
import numpy as np
import pandas as pd

In [35]:
df=pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [36]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [37]:
df.dropna()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [38]:
df=df.drop(columns=['Surname'])
df.head(5)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [39]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [40]:
df['Gender']=le.fit_transform(df['Gender'])
df['Geography']=le.fit_transform(df['Geography'])

In [41]:
df.head(5)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [42]:
x=df.drop(columns=['Exited'])
y=df['Exited']

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [45]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [46]:
x_train_sc=sc.fit_transform(x_train)

In [47]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)
x_train_new.head(5)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0.831470,-0.202167,0.169582,1.519198,-1.091687,-0.464608,0.006661,-1.215717,0.809503,0.642595,-1.032270,1.106432
1,1.483423,0.807044,-2.304559,0.313126,0.916013,0.301026,-1.377440,-0.006312,-0.921591,0.642595,0.968738,-0.748664
2,-0.687448,-1.519081,-1.191196,-0.892945,-1.091687,-0.943129,-1.031415,0.579935,-0.921591,0.642595,-1.032270,1.485335
3,0.114875,1.241115,0.035566,1.519198,0.916013,0.109617,0.006661,0.473128,-0.921591,0.642595,-1.032270,1.276528
4,-1.599698,-1.110869,2.056114,1.519198,-1.091687,1.736588,1.044737,0.810193,0.809503,0.642595,0.968738,0.558378

In [48]:
np.round(x_train_new.describe(),2)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,0.00,0.00,0.00,-0.00,0.00,0.00,0.00,0.00,-0.00,0.00,0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.72,-1.75,-3.10,-0.89,-1.09,-2.00,-1.72,-1.22,-0.92,-1.56,-1.03,-1.74
25%,-0.87,-0.87,-0.70,-0.89,-1.09,-0.66,-1.03,-1.22,-0.92,-1.56,-1.03,-0.85
50%,0.00,0.01,0.01,-0.89,0.92,-0.18,0.01,0.33,-0.92,0.64,0.97,0.00
75%,0.87,0.86,0.70,0.31,0.92,0.49,0.70,0.82,0.81,0.64,0.97,0.86
max,1.73,1.73,2.06,1.52,0.92,4.70,1.74,2.59,4.27,0.64,0.97,1.73

In [61]:
df=pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [62]:
df=df.drop(columns=['Surname'])
df.head(5)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [55]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [63]:
from sklearn.preprocessing import OrdinalEncoder

In [64]:
oe=OrdinalEncoder(categories=[['Male','Female'],['France','Spain','Germany']])

In [66]:
oe_arr=oe.fit_transform(df[['Gender','Geography']])

In [58]:
oe_arr_df=pd.DataFrame(oe_arr,columns=['Gender','Geography'])

In [67]:
oe_arr_df.head(5)

   Gender  Geography
0     1.0        0.0
1     1.0        1.0
2     1.0        0.0
3     1.0        0.0
4     1.0        1.0

In [68]:
df.head(5)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [70]:
a=pd.get_dummies(df,columns=['Geography','Gender'])

In [71]:
a.head(5)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1,True,False,False,True,False
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0,False,False,True,True,False
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1,True,False,False,True,False
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0,True,False,False,True,False
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0,False,False,True,True,False

In [72]:
a.astype(int)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,1,15634602,619,42,2,0,1,1,1,101348,1,1,0,0,1,0
1,2,15647311,608,41,1,83807,1,0,1,112542,0,0,0,1,1,0
2,3,15619304,502,42,8,159660,3,1,0,113931,1,1,0,0,1,0
3,4,15701354,699,39,1,0,2,0,0,93826,0,1,0,0,1,0
4,5,15737888,850,43,2,125510,1,1,1,79084,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0,2,1,0,96270,0,1,0,0,0,1
9996,9997,15569892,516,35,10,57369,1,1,1,101699,0,1,0,0,0,1
9997,9998,15584532,709,36,7,0,1,0,1,42085,1,1,0,0,1,0
9998,9999,15682355,772,42,3,75075,2,1,0,92888,1,0,1,0,0,1
9999,10000,15628319,792,28,4,130142,1,1,0,38190,0,1,0,0,1,0

In [73]:
b=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [74]:
b.astype(int)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,1,15634602,619,42,2,0,1,1,1,101348,1,0,0,0
1,2,15647311,608,41,1,83807,1,0,1,112542,0,0,1,0
2,3,15619304,502,42,8,159660,3,1,0,113931,1,0,0,0
3,4,15701354,699,39,1,0,2,0,0,93826,0,0,0,0
4,5,15737888,850,43,2,125510,1,1,1,79084,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0,2,1,0,96270,0,0,0,1
9996,9997,15569892,516,35,10,57369,1,1,1,101699,0,0,0,1
9997,9998,15584532,709,36,7,0,1,0,1,42085,1,0,0,0
9998,9999,15682355,772,42,3,75075,2,1,0,92888,1,1,0,1
9999,10000,15628319,792,28,4,130142,1,1,0,38190,0,0,0,0